### ISSUE TITLE
Fail to run cloned project

### ISSUE THREAD

**Issue by lechnerc77** [aaronpowell/azure-functions-nodejs-openapi#3]
## Procedure 

- I clone the repository as is and would like to try out the examples provided by the repo.
- I install the dependencies in the root directory via `npm install` 
- I open one of the examples and do an `npm install` e.g. in v3.1. This install the package dependency to azure-functions-nodejs-openapi via symlink into the nodes_modules folder
- I do not use the devcontainer

## Result

- VSCode does not resolve import from `azure-functions-nodejs-openapi`
- `npm run build` throws an error: Cannot find module 'azure-functions-nodejs-openapi' or its corresponding type declarations

When using the devcontainer the start-up of the devcontainer throws the error `Error: Command failed: /bin/sh -c npm install -g npm@latest && npm install` 
After manual execution of an npm install the `npm run build` fials with the same error as above.

Maybe I am missing something basic here. Any hints appreciated.

**Comment by aaronpowell** [comment]
did you run `npm run build` at the root of the repo? It needs to compile the TS for the package before it can run the example

**Comment by lechnerc77** [comment]
Thanks for the hint, I knew it was something obvious :-)

However that only partially did the trick: on windows the clean script `rm -rf dist` does not work and throws an error. 
Potential fix: using `del-cli` as dev dependency would make it OS agnostic. What's your take on that.

I am also not sure if you want to remove the `build` directory instead of the `dist`

Concerning the error with the dev container: I think that is an issue with the used node version of the Docker Image. Switching to 14 resolves the error.

Happy to hear your feedback on the three points

**Comment by aaronpowell** [comment]
Ha yeah, should probably be doing some testing on Windows 😅. I work exclusively in WSL2 or in Docker, never on my Windows host directly!

**Comment by lechnerc77** [comment]
I thought so, when coming across the points ;-)
I will create a pull request for each point spotted (soon .. probably this week)

**Comment by aaronpowell** [comment]
I've added Windows to the build matrix and fixed the `clean` script to be xplat, so we shouldn't have this again.

**Comment by lechnerc77** [comment]
I confirm, works now
