### ISSUE TITLE
OAS version mismatch

### ISSUE THREAD

**Issue by Jonatan-V** [aaronpowell/azure-functions-nodejs-openapi#5]
Hi
There is currently a mismatch between the OAS versions in the project
Current: [openAPIv3.ts](https://github.com/aaronpowell/azure-functions-nodejs-openapi/blob/main/src/openAPIv3.ts) = 3.0.0 and [openAPIv3_1.ts](https://github.com/aaronpowell/azure-functions-nodejs-openapi/blob/main/src/openAPIv3_1.ts) = 3.0.3
Expected: [openAPIv3.ts](https://github.com/aaronpowell/azure-functions-nodejs-openapi/blob/main/src/openAPIv3.ts) = 3.0.3 and [openAPIv3_1.ts](https://github.com/aaronpowell/azure-functions-nodejs-openapi/blob/main/src/openAPIv3_1.ts) = 3.1.0

**Comment by aaronpowell** [comment]
Should be sorted with `v0.3.0`
