### ISSUE TITLE
output overwrite issue

### ISSUE THREAD

**Issue by Jonatan-V** [aaronpowell/azure-functions-nodejs-openapi#6]
Hi
Currently if you have multiple functions with the same path but different methods/verbs, the output swagger will overwrite the functions with the same path. It would be great if it could merge them in stead so its possible to use both patterns of writing functions with single methods/verbs as well as functions with collection of methods/verbs.

This works:
func.js - path: /pet - method: get, post
func2.js - path /pet/{name} - method: get, patch, delete

This doesnt (overwrite issue):
func.js - path: /pet - method: get
func2.js - path: /pet - method: post
func3.js - path /pet/{name} - method: get
func4.js - path /pet/{name} - method: patch
func5.js - path /pet/{name} - method: delete

Regards Jonatan

**Comment by aaronpowell** [comment]
Should be sorted wit `v0.3.0`
